### ISSUE TITLE
Create Employee Form

### ISSUE THREAD

**Issue by budandan** [budandan/INTEX-2017#2]
1. Scaffold the Employee Controller using a mapped model
2. Add form validation to all fields
3. Make the Role field a dropdown menu that can select:
   - Sales Agent: id = "SalesAgent"
   - Lab Technician: id = "LabTech"
   - Billing: id = "Billing"
   - System Admin:id = "SysAdmin"
   - Reports: id = "Reports"

**Comment by barelylegit** [comment]
Completed and pushed the branch
